platform :ios,'11.0'
inhibit_all_warnings!
target 'TikTok' do
    pod 'Alamofire'
    pod 'HandyJSON'
    pod 'SnapKit'
    pod 'Starscream'
    pod 'libwebp'
    pod 'SnapKit'
    pod 'Moya'
    pod 'MJRefresh'
    pod 'SwiftLint'
    pod 'SDWebImage'
    pod 'YYKit'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
